import Link from "next/link";
import Breadcrumb from "@/components/ui/Breadcrumb";

export const metadata = {
  title: "Terms of Service - Thumb-Free",
  description:
    "Read our Terms of Service to understand the rules and guidelines for using Thumb-Free AI Thumbnail Generator.",
};

export default function TermsPage() {
  const effectiveDate = "January 31, 2026";

  return (
    <div className="min-h-screen bg-background py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        {/* Breadcrumb */}
        <Breadcrumb
          items={[{ label: "Home", href: "/" }, { label: "Terms of Service" }]}
        />

        {/* Content Card */}
        <div className="bg-[#1A1A1A] rounded-3xl p-8 sm:p-12 lg:p-16">
          {/* Title */}
          <h1 className="text-white font-bold text-3xl sm:text-4xl lg:text-5xl leading-tight mb-4">
            Terms of Service
          </h1>

          {/* Effective Date */}
          <p className="text-sm text-muted-foreground mb-12">
            Last updated: {effectiveDate}
          </p>

          {/* Content Sections */}
          <div className="space-y-8">
            {/* Introduction */}
            <section>
              <h2 className="text-white font-semibold text-xl mb-4">
                1. Introduction
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                Welcome to Thumb-Free ("we," "our," or "us"). These Terms of
                Service ("Terms") govern your use of our AI-powered YouTube
                thumbnail generation service. By accessing or using Thumb-Free,
                you agree to be bound by these Terms.
              </p>
            </section>

            {/* Service Description */}
            <section>
              <h2 className="text-white font-semibold text-xl mb-4">
                2. Service Description
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Thumb-Free provides an AI-powered tool that generates YouTube
                thumbnails based on your video titles and uploaded images. Our
                service includes:
              </p>
              <ul className="list-disc list-inside text-muted-foreground leading-relaxed space-y-2 ml-4">
                <li>AI-generated thumbnail designs</li>
                <li>Multiple thumbnail variations per request</li>
                <li>Customizable styling options</li>
                <li>High-resolution image exports</li>
              </ul>
            </section>

            {/* User Responsibilities */}
            <section>
              <h2 className="text-white font-semibold text-xl mb-4">
                3. User Responsibilities
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                By using Thumb-Free, you agree to:
              </p>
              <ul className="list-disc list-inside text-muted-foreground leading-relaxed space-y-2 ml-4">
                <li>
                  Provide accurate and truthful information when using our
                  service
                </li>
                <li>Only upload images that you have the right to use</li>
                <li>
                  Not use our service for any unlawful or fraudulent purposes
                </li>
                <li>Respect the intellectual property rights of others</li>
                <li>
                  Not attempt to circumvent any usage limits or restrictions
                </li>
              </ul>
            </section>

            {/* Intellectual Property */}
            <section>
              <h2 className="text-white font-semibold text-xl mb-4">
                4. Intellectual Property
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                You retain ownership of the content you upload to Thumb-Free.
                However, you grant us a license to use, process, and store your
                content solely for the purpose of providing our services.
              </p>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Thumbnails generated by our service are owned by you. You have
                full rights to use, modify, and distribute the generated
                thumbnails for any purpose, including commercial use on YouTube
                and other platforms.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                Thumb-Free and all related logos, designs, and features are our
                intellectual property and protected by applicable laws.
              </p>
            </section>

            {/* Limitation of Liability */}
            <section>
              <h2 className="text-white font-semibold text-xl mb-4">
                5. Limitation of Liability
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                To the fullest extent permitted by law, Thumb-Free shall not be
                liable for:
              </p>
              <ul className="list-disc list-inside text-muted-foreground leading-relaxed space-y-2 ml-4">
                <li>
                  Any indirect, incidental, special, or consequential damages
                </li>
                <li>Loss of data, profits, or business opportunities</li>
                <li>The quality or performance of generated thumbnails</li>
                <li>
                  Actions taken by third parties based on your use of our
                  service
                </li>
              </ul>
            </section>

            {/* Termination */}
            <section>
              <h2 className="text-white font-semibold text-xl mb-4">
                6. Termination
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                We reserve the right to suspend or terminate your access to
                Thumb-Free at any time, with or without cause, with or without
                notice. Upon termination, your right to use the service will
                immediately cease.
              </p>
            </section>

            {/* Changes to Terms */}
            <section>
              <h2 className="text-white font-semibold text-xl mb-4">
                7. Changes to These Terms
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                We may update these Terms from time to time. We will notify you
                of any material changes by posting the new Terms on our website
                and updating the "Last updated" date. Your continued use of the
                service after such changes constitutes acceptance of the new
                Terms.
              </p>
            </section>

            {/* Contact */}
            <section>
              <h2 className="text-white font-semibold text-xl mb-4">
                8. Contact Us
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                If you have any questions about these Terms, please contact us
                at{" "}
                <a
                  href="mailto:support@thumb-free.com"
                  className="text-white hover:text-white/80 transition-colors duration-200"
                >
                  support@thumb-free.com
                </a>
              </p>
            </section>
          </div>
        </div>

        {/* Back to Home Link */}
        <div className="mt-8 text-center">
          <Link
            href="/"
            className="inline-flex items-center text-muted-foreground hover:text-foreground transition-colors duration-200"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-4 h-4 mr-2"
              aria-hidden="true"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18"
              />
            </svg>
            Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
